FROM python

WORKDIR /app

ADD ./feature_extractor.py /app/feature_extractor.py
ADD ./phrase_clf1.joblib /app/phrase_clf1.joblib
ADD ./person_clf.joblib /app/person_clf.joblib

COPY ./req.txt /app/req.txt
COPY ./src /app/src

RUN pip install --no-cache-dir -r /app/req.txt

CMD [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80" ]