FROM python

WORKDIR /app

ADD ./augmentation.py /app/augmentation.py
ADD ./feature_extractor.py /app/feature_extractor.py
ADD ./data/data_for_api.csv /app/data_for_api.csv

COPY ./req.txt /app/req.txt
COPY ./src /app/src

RUN pip install --no-cache-dir -r /app/req.txt

CMD [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80" ]